name: Update Repo with Latest Changes
on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  change-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run update Script
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config pull.ff only
          ./repo_scripts/update_branch.sh
